CREATE TABLE USUARIO 
(
ID_USUARIO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
TIPO_USUARIO INT,
USUARIO VARCHAR(100),
PASS VARCHAR(100),
NOMBRE VARCHAR(100),
APELLIDO VARCHAR(100),
TELEFONO VARCHAR(100),
CORREO VARCHAR(100),
FECHA_NACIMIENTO DATE,
ESTADO TINYINT DEFAULT 0,
FECHA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO `USUARIO`(`TIPO_USUARIO`, `USUARIO`, `PASS`, `NOMBRE`, `APELLIDO`, `TELEFONO`, `CORREO`, `FECHA_NACIMIENTO`, `ESTADO`)
VALUES (1,'admin','admin','DAVID','QUINTEROS','72158808','david.quinteros.2131@gmail.com','1995-07-04',1);

CREATE TABLE `heroku_c15972f22ac9d85`.`tipo_usuario` (
  `ID_TIPO_USUARIO` INT NOT NULL AUTO_INCREMENT,
  `DESCRIPCION` VARCHAR(100) NULL,
  `ESTADO` DECIMAL(1) NULL,
  `FECHA_REGISTRO` DATE NULL,
  PRIMARY KEY (`ID_TIPO_USUARIO`));


CREATE TABLE TIPO_USUARIO 
(
ID_TIPO_USUARIO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
DESCRIPCION VARCHAR(100),
ESTADO TINYINT DEFAULT 0
FECHA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE MEDICO 
(
ID_MEDICO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
NOMBRE VARCHAR(100),
APELLIDO VARCHAR(100),
TELEFONO VARCHAR(100),
CORREO VARCHAR(100),
FECHA_NACIMIENTO DATE,
FECHA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE CLIENTE 
(
ID_CLIENTE INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
NOMBRE VARCHAR(100),
APELLIDO VARCHAR(100),
TELEFONO VARCHAR(100),
CORREO VARCHAR(100),
FECHA_NACIMIENTO DATE,
FECHA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);